version: '3.9'

networks:
  movie-network:
    driver: bridge

services:
  movie_service:
    build:
      context: ./movies-crud
      dockerfile: Dockerfile
    environment:
      DB_HOST: movie_db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: moviesdb
    depends_on:
      - movie_db
    # ports:
    #   - 8003:8000
    networks:
      - movie-network

  reviews_service:
    build:
      context: ./movies-reviews
      dockerfile: Dockerfile
    environment:
      DB_HOST: movie_db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: moviesdb
    depends_on:
      - movie_db
    # ports:
    #   - 8004:8000
    networks:
      - movie-network

  recommendation_service:
    build:
      context: ./movies-recommendation
      dockerfile: Dockerfile
    depends_on:
      - movie_db
    # ports:
    #   - 8005:8000
    networks:
      - movie-network
    
  movie_db:
    image: postgres:12.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=moviesdb
    ports:
      - 5432:5432
    networks:
      - movie-network

  kong:
    image: kong:latest
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/etc/kong/kong.yml
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
    volumes:
      - ./kong.yml:/etc/kong/kong.yml
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 8444:8444
    networks:
      - movie-network

