version: '3.7'

services:
  movie_service:
    build:
      context: ./movies-crud
      dockerfile: Dockerfile
    environment:
      DB_HOST: movie_db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: moviesdb
    depends_on:
      - movie_db
    ports:
      - 8000:8000
    networks:
      - movie-network
  reviews_service:
    build:
      context: ./movies-reviews
      dockerfile: Dockerfile
    environment:
      DB_HOST: movie_db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: moviesdb
    depends_on:
      - movie_db
    ports:
      - 8001:8001
    networks:
      - movie-network

  recommendation_service:
    build:
      context: ./movies-recommendation
      dockerfile: Dockerfile
    depends_on:
      - movie_db
    ports:
      - 8002:8002
    networks:
      - movie-network
    
  movie_db:
    image: postgres:12.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=moviesdb
    ports:
      - 5432:5432
    networks:
      - movie-network

  keycloak:
    image: jboss/keycloak
    environment:
      - KEYCLOAK_USER:admin
      - KEYCLOAK_PASSWORD:admin
      - DB_VENDOR=POSTGRES
      - DB_ADDR=movie_db  # Use the name of the database service
      - DB_PORT=5432
      - DB_DATABASE=moviesdb  # Use the same database name as my existing services
      - DB_USER=postgres  # Use the same database user as my existing services
      - DB_PASSWORD=postgres
      - PROXY_ADDRESS_FORWARDING=true
    depends_on:
      - movie_db
    ports:
      - 8080:8080
    networks:
      - movie-network

  # keycloak:
  #   image: jboss/keycloak:latest
  #   environment:
  #     - KEYCLOAK_USER=admin
  #     - KEYCLOAK_PASSWORD=admin
  #     - DB_VENDOR=POSTGRES
  #   #  KEYCLOAK_USER: admin     # Set your desired Keycloak admin username
  #   #  KEYCLOAK_PASSWORD: admin # Set your desired Keycloak admin password
  #   #  DB_VENDOR=POSTGRES
  #   ports:
  #     - 8080:8080
  #   networks:
  #     - movie-network

networks:
  movie-network:
